name: AutoZipCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip Folder
        run: zip -r release.zip ./src ./manifest.json
      - name: Release to Github
        run: echo "Release"
