name: AutoZipCI on ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r release.zip ./src ./manifest.json
      - name: Release to Github
        run: echo "Release"
